from pathlib import Path

CORPUS = Path(r"C:\Users\USER\Desktop\Extras\i-oska\Vibhu-Oska\Data\training\karsh\corpus.txt")
existing = CORPUS.read_text(encoding="utf-8")
count = existing.count("Query:")

extra = [
    "Query: what is python __del__",
    "Response: __del__ is called when an object is garbage collected. Use context managers instead.",
    "",
    "Query: what is python super()",
    "Response: super() calls parent class methods to extend rather than replace.",
    "",
    "Query: what is python isinstance",
    "Response: isinstance(obj, Class) checks if obj is instance of Class or subclasses.",
    "",
    "Query: what is python issubclass",
    "Response: issubclass(Sub, Parent) checks if Sub inherits from Parent.",
    "",
    "Query: what is python type()",
    "Response: type(obj) returns class. type(name, bases, dict) creates classes dynamically.",
    "",
    "Query: what is python callable",
    "Response: callable(obj) checks if obj has __call__ method.",
    "",
    "Query: what is python iter()",
    "Response: iter(obj) returns iterator. Calls __iter__().",
    "",
    "Query: what is python next()",
    "Response: next(iterator) returns next item. next(iterator, default) returns default if exhausted.",
    "",
    "Query: what is python enumerate",
    "Response: enumerate(iterable, start=0) yields (index, value) pairs.",
    "",
    "Query: what is python zip",
    "Response: zip(iter1, iter2) pairs elements. Stops at shortest iterable.",
    "",
    "Query: what is python map",
    "Response: map(function, iterable) applies function to each element.",
    "",
    "Query: what is python filter",
    "Response: filter(function, iterable) keeps elements where function returns True.",
    "",
    "Query: what is python reduce",
    "Response: reduce(function, iterable) accumulates into single value. Import from functools.",
    "",
    "Query: what is python any()",
    "Response: any(iterable) returns True if any element is truthy.",
    "",
    "Query: what is python all()",
    "Response: all(iterable) returns True if all elements are truthy.",
    "",
    "Query: what is python sorted",
    "Response: sorted(iterable, key=func) returns new sorted list.",
    "",
    "Query: what is python reversed",
    "Response: reversed(iterable) returns reverse iterator.",
    "",
    "Query: what is python min max sum",
    "Response: min/max/sum take iterable and optional key function.",
    "",
    "Query: what is python abs",
    "Response: abs(x) returns absolute value. Works with int, float, complex.",
    "",
    "Query: what is python round",
    "Response: round(x, digits) rounds to specified decimal places.",
    "",
    "Query: what is python pow",
    "Response: pow(base, exp, mod=None) raises to power. Optional modulus for large numbers.",
    "",
    "Query: what is python divmod",
    "Response: divmod(a, b) returns (quotient, remainder) tuple.",
    "",
    "Query: what is python format",
    "Response: format(value, spec) formats value. f-strings use this internally.",
    "",
    "Query: what is python chr ord",
    "Response: chr(n) converts int to character. ord(c) converts character to int.",
    "",
    "Query: what is python hex oct bin",
    "Response: hex/oct/bin convert int to hex/octal/binary string representation.",
    "",
    "Query: what is python id",
    "Response: id(obj) returns unique identity of object. Stays same during lifetime.",
    "",
    "Query: what is python hash",
    "Response: hash(obj) returns hash value. Required for dict keys and set elements.",
    "",
    "Query: what is python vars",
    "Response: vars(obj) returns __dict__ of object. Useful for debugging.",
]

extra_section = "\n".join(extra)
with open(CORPUS, "a", encoding="utf-8") as f:
    f.write("\n\n" + extra_section + "\n")

final = CORPUS.read_text(encoding="utf-8").count("Query:")
print(f"{count} -> {final} Q&A pairs ({CORPUS.stat().st_size:,} bytes)")
